Repository saveourtool/save-cloud, pull requests merged in 2022-12, with the labels that each got.

#1543 Remove diktat-cli and change demo port
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application.yml
  docker-compose.yaml
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractFileBasedStorage.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt
  save-demo/src/main/resources/application.properties
  save-demo/src/main/resources/diktat
  save-demo/src/main/resources/diktat.cmd
  save-demo/src/main/resources/ktlint-cli
  save-demo/src/main/resources/ktlint-cli.cmd
  save-frontend/webpack.config.d/dev-server.js
Labels: enhancement

#1547 [CPG] `layout-forceatlas2`
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgResult.kt
  save-frontend/build.gradle.kts
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutCircular.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutForceAtlas2.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutInstance.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/layouts/LayoutRandom.kt
  yarn.lock
Labels: enhancement, frontend

#1548 [DEMO] kubernetes and demo friends forever
  save-cloud-charts/save-cloud/templates/demo-configmap.yaml
  save-cloud-charts/save-cloud/templates/demo-deployment.yaml
  save-cloud-charts/save-cloud/templates/demo-service.yaml
  save-cloud-charts/save-cloud/templates/fs-storage-pvc.yaml
  save-cloud-charts/save-cloud/values-minikube.yaml
  save-cloud-charts/save-cloud/values.yaml
Labels: infra

#1561 Increase demo pod memory
  save-cloud-charts/save-cloud/templates/demo-deployment.yaml
Labels: infra

#1566 Provide launch logs
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoResult.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DiktatDemoService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DiktatDemoComponent.kt
Labels: enhancement

#1567 [DEMO] Fix logs display on FE
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DiktatDemoComponent.kt
Labels: bug, frontend

#1582 [DEMO] Major diktat-demo improvements
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DemoAdditionalParams.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoResult.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DiktatDemoController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DiktatDemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/TopBar.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DiktatDemoComponent.kt
Labels: enhancement

#1584 [DEMO] hotfix for DIKTAT_CONFIG_NAME
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
Labels: bug

#1592 [CPG] react-sigma events
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphEvents.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphLoader.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/sigma/ReactSigma.kt
Labels: enhancement, frontend

#1596 [CPG] parallel edges workaround
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphEvents.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
Labels: enhancement, frontend

#1591 Renaming AgentContainerId to ContainerId
  db/test-data/sqlRequests/test.csv
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/AgentConfiguration.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/Utils.kt
  save-agent/src/linuxX64Test/kotlin/com/saveourtool/save/agent/SaveAgentTest.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestExecutionController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/AgentsController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/AgentRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestExecutionRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestExecutionService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestService.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/AgentsControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestExecutionControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestInitializeControllerTest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/agent/AgentEnvName.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/agent/Heartbeat.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/AgentsController.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/controller/HeartbeatController.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerRunner.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/runner/ContainerRunner.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/runner/ContainerRunnerException.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/AgentService.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/HeartBeatInspector.kt
  save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/agents/AgentsControllerTest.kt
  save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/controller/heartbeat/HeartbeatControllerTest.kt
  save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/docker/DockerContainerManagerTest.kt
  save-orchestrator-common/src/test/kotlin/com/saveourtool/save/orchestrator/service/ContainerServiceTest.kt
  save-orchestrator/src/main/kotlin/com/saveourtool/save/orchestrator/service/BackendOrchestratorAgentService.kt
Labels: refactoring

#1603 [CPG] Replace button text with icon
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/fontawesome/Icons.kt
Labels: frontend

#1620 [CPG] Layout selector
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/cpg/CpgGraph.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/cpg/GraphLoader.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/demo/CpgView.kt
Labels: enhancement, frontend

#1623 `SAVE on GitHub` button color in top bar
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarLinks.kt
Labels: bug, frontend

#1629 [DEMO] db support ph.I
  build.gradle.kts
  buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DatabaseUtils.kt
  save-demo/build.gradle.kts
  save-demo/db/db.changelog-demo.xml
  save-demo/db/tables/db.changelog-tables.xml
  save-demo/db/tables/dependency.xml
  save-demo/db/tables/git-repo.xml
  save-demo/db/tables/snapshot.xml
  save-demo/db/tables/tool.xml
  save-demo/src/main/resources/application-dev.properties
  save-demo/src/main/resources/application-prod.properties
  save-demo/src/main/resources/application.properties
Labels: enhancement

#1637 [DEMO] db support ph.II
  save-demo/db/tables/dependency.xml
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/GithubRepo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/ReleaseAsset.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/ReleaseMetadata.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Snapshot.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Tool.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/GithubRepoRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/SnapshotRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/ToolRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubRepoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/SnapshotService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
  save-demo/src/main/resources/application.properties
Labels: enhancement

#1644 [DEMO] db support ph.III
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
  authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/configs/ConfigProperties.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-backend/src/main/resources/application-dev.properties
  save-backend/src/main/resources/application.properties
  save-backend/src/test/resources/application.properties
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/NewDemoToolRequest.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/GithubRepo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
Labels: enhancement

#1648 [DEMO] db support ph.IV
  save-cloud-charts/save-cloud/templates/demo-configmap.yaml
  save-cloud-charts/save-cloud/templates/demo-deployment.yaml
  save-cloud-charts/save-cloud/templates/mysql-deployment.yaml
  save-cloud-charts/save-cloud/values.yaml
Labels: enhancement, infra

#1651 [DEMO] hotfix for db support ph.IV
  docker-compose.yaml
  save-cloud-charts/save-cloud/README.md
  save-cloud-charts/save-cloud/templates/demo-deployment.yaml
  save-demo/src/main/resources/META-INF/spring.factories
Labels: infra

#1652 [DEMO] hotfix (2) for db support ph.IV
  save-demo/build.gradle.kts
  save-demo/src/main/resources/bootstrap.yml
Labels: infra

#1659 Suppress `DSL_SCOPE_VIOLATION` in `.kts` scrips
  authentication-service/build.gradle.kts
  build.gradle.kts
  save-agent/build.gradle.kts
  save-api-cli/build.gradle.kts
  save-api/build.gradle.kts
  save-backend/build.gradle.kts
  save-cloud-common/build.gradle.kts
  save-demo-cpg/build.gradle.kts
  save-demo/build.gradle.kts
  save-orchestrator-common/build.gradle.kts
  save-orchestrator/build.gradle.kts
  save-preprocessor/build.gradle.kts
  save-sandbox/build.gradle.kts
Labels: infra

#1664 Update the documentation
  save-deploy/README.md
Labels: documentation

#1668 [DEMO] ProjectDemoMenu
  db/v-2/tables/db.changelog-tables.xml
  db/v-2/tables/lnk-project-github.xml
  db/v-2/tables/project.xml
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkProjectGithubRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkProjectGithubService.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/ProjectControllerTest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoInfo.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoStatus.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/NewDemoToolRequest.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/LnkProjectGithub.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubRepoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ProjectView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/ProjectMenuBar.kt
Labels: enhancement, help wanted

#1672 Refactored DtoWithId
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/DtoWithId.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuiteDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuitesSourceDto.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuite.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuitesSource.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/spring/entity/BaseEntityWithDto.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/spring/entity/BaseEntityWithDtoWithId.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/TestSuitesSourcesDisplayer.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuitessources/TestSuiteSourceUpsertComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
Labels: refactoring

#1674 Refactored ExecutionService
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/RunExecutionController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkContestExecutionService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
Labels: refactoring

#1680 Added `FileController`
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DownloadFilesController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/FileController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/FileInternalController.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
  save-backend/src/test/resources/save-1.0-linuxX64.kexe
  save-backend/src/test/resources/save-agent.kexe
Labels: refactoring

#1681 [DEMO] saveourtool projects instead of GitHub projects
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkProjectGithubService.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoInfo.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/NewDemoToolRequest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/ProjectCoordinates.kt
  save-demo/db/tables/db.changelog-tables.xml
  save-demo/db/tables/demo.xml
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Demo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/GithubRepo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/DemoRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
Labels: enhancement
