Repository saveourtool/save-cloud, pull requests merged in 2023-02, with the labels that each got.

#1794 save-demo-agent configuration
  save-demo-agent/build.gradle.kts
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/DemoAgentConfig.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Server.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/ConfigUtils.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
  save-demo-agent/src/nativeTest/kotlin/com/saveoourtool/save/demo/agent/MainTest.kt
  save-demo-agent/src/nativeTest/kotlin/com/saveoourtool/save/demo/agent/ServerTest.kt
Labels: enhancement

#1811 Toml instead of Properties
  save-agent/build.gradle.kts
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/Main.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/Requests.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/SaveAgent.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/FileUtils.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/HttpUtils.kt
  save-agent/src/commonTest/kotlin/com/saveourtool/save/agent/SaveAgentTest.kt
  save-agent/src/jvmMain/kotlin/com/saveourtool/save/agent/utils/FileUtils.kt
  save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/utils/FileUtils.kt
  save-cloud-common/build.gradle.kts
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/jsMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-demo-agent/build.gradle.kts
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/ConfigUtils.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt
Labels: refactoring

#1809 Docker compose
  buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt
  save-deploy/README.md
Labels: infra

#1824 [DEMO] file uploading updates
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/SimpleFileUploader.kt
Labels: enhancement

#1816 save-demo-agent server
  gradle/libs.versions.toml
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/Requests.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/FileUtils.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/HttpUtils.kt
  save-agent/src/jvmMain/kotlin/com/saveourtool/save/agent/utils/FileUtils.kt
  save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/utils/FileUtils.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt
  save-cloud-common/build.gradle.kts
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/ArchiveUtils.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/HttpUtils.kt
  save-cloud-common/src/jsMain/kotlin/com/saveourtool/save/utils/ArchiveUtils.kt
  save-cloud-common/src/jsMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ArchiveUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/ArchiveUtils.kt
  save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-demo-agent/build.gradle.kts
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/DemoAgentConfig.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Server.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/SimpleRunner.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/HttpUtils.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
  yarn.lock
Labels: enhancement

#1835 Batch size input form fix
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestResourcesSelection.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectRunMenu.kt
Labels: frontend

#1838 Upload save-demo-agent.kexe
  .github/workflows/deploy_images.yml
Labels: infra

#1849 [DEMO] DependencyController
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
Labels: refactoring

#1851 Fix the deprecation warnings in `Arrow.kt` usages
  save-api/src/main/kotlin/com/saveourtool/save/api/SaveCloudClient.kt
  save-api/src/main/kotlin/com/saveourtool/save/api/impl/DefaultSaveCloudClient.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/utils/ArrowUtils.kt
  save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/controller/CpgController.kt
  save-demo-cpg/src/main/kotlin/com/saveourtool/save/demo/cpg/utils/Neo4jUtils.kt
Labels: infra

#1850 save-demo-agent-distribution
  .github/workflows/deploy_images.yml
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-demo-agent/build.gradle.kts
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
  save-demo-agent/src/nativeMain/resources/agent.toml
Labels: infra

#1810 Implement the `useEventStream()` (SSE, HTTP GET only) and `useNewlineDelimitedJson()` React hooks
  save-backend/src/main/kotlin/com/saveourtool/save/backend/utils/HttpUtils.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/utils/ResponseWithTiming.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/utils/ServerTiming.kt
  save-frontend/build.gradle.kts
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/CustomHooks.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/Utils.kt
  save-frontend/src/test/kotlin/com/saveourtool/save/frontend/utils/ServerSentEventTest.kt
  save-frontend/src/test/kotlin/com/saveourtool/save/frontend/utils/TestMessage.kt
Labels: frontend

#1853 save-demo-agent-configuration.gradle.kts
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-demo-agent-configuration.gradle.kts
  save-demo/build.gradle.kts
Labels: infra

#1855 Move `Flow<Byte>.decodeToString()` to :save-cloud-common
  gradle/libs.versions.toml
  save-cloud-common/build.gradle.kts
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/coroutines/flow/Flow.kt
  save-cloud-common/src/commonTest/kotlin/com/saveourtool/save/coroutines/flow/FlowTest.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
Labels: refactoring

#1861 Correct the path/URL manupulation when `saveDemoAgentDistroFileUrl` is unset
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/DownloadConfiguration.kt
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-agent-configuration.gradle.kts
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-demo-agent-configuration.gradle.kts
Labels: infra

#1854 s3-deployment.yaml
  buildSrc/src/main/kotlin/com/saveourtool/save/buildutils/DockerStackConfiguration.kt
  save-backend/src/main/resources/application-dev.properties
  save-backend/src/test/resources/application.properties
  save-backend/src/test/resources/docker-compose.yaml
  save-cloud-charts/save-cloud/templates/s3-deployment.yaml
  save-cloud-charts/save-cloud/templates/s3-service.yaml
  save-cloud-charts/save-cloud/values-minikube.yaml
  save-cloud-charts/save-cloud/values.yaml
  save-demo/src/main/resources/application-dev.properties
  save-sandbox/src/main/resources/application-dev.properties
Labels: help wanted, infra

#1868 Rewrite `Flow<Byte>.decodeToString()` using `okio.Buffer`
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/coroutines/flow/Flow.kt
Labels: frontend

#1869 demo orchestrator
  gradle/libs.versions.toml
  save-cloud-charts/save-cloud/templates/demo-configmap.yaml
  save-cloud-charts/save-cloud/templates/demo-deployment.yaml
  save-cloud-charts/save-cloud/templates/demo-service-account.yaml
  save-cloud-charts/save-cloud/templates/mysql-deployment.yaml
  save-cloud-charts/save-cloud/templates/sandbox-deployment.yaml
  save-cloud-charts/save-cloud/values-minikube.yaml
  save-cloud-common/build.gradle.kts
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoAgentConfig.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/Sdk.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/KotlinUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/SpringUtils.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Server.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/SimpleRunner.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
  save-demo-agent/src/nativeTest/kotlin/com/saveoourtool/save/demo/agent/ServerTest.kt
  save-demo/build.gradle.kts
  save-demo/src/main/kotlin/com/saveourtool/save/demo/config/Beans.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementApiController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Demo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DownloadToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesRunnerException.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
  save-demo/src/main/resources/application-dev.properties
  save-demo/src/main/resources/application.properties
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/config/Beans.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt
Labels: enhancement, help wanted

#1874 PodRunner implementation
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DemoController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DiktatDemoController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/DefaultRunnerFactory.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/Runner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/RunnerFactory.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/AbstractCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/CliRunnerFactory.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DefaultCliRunnerFactory.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DemoCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/pod/DemoPodRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/pod/PodRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/AbstractDemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DiktatDemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DownloadToolService.kt
Labels: enhancement

#1875 save-demo-agent wrong exception catching
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/FileUtils.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
Labels: bug

#1876 Download save-demo-agent to pod
  save-cloud-charts/save-cloud/templates/demo-configmap.yaml
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/AgentDownloadUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
  save-demo/src/main/resources/application-dev.properties
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/service/ContainerService.kt
Labels: enhancement

#1885 save-demo interacts with save-demo-agent
  save-cloud-charts/save-cloud/templates/demo-service-account.yaml
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/KotlinUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/AgentDownloadUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/ReactorUtils.kt
  save-demo-agent/build.gradle.kts
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/SetupUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DemoController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementApiController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Demo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/pod/DemoPodRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/pod/PodRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
Labels: enhancement

#1896 okio-extras
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: infra

#1899 save-demo cleanup
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DependencyController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/GithubRepoRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/SnapshotRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/ToolRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubRepoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/SystemUtils.kt
Labels: refactoring

#1901 Hotfix for loki deployment
  save-cloud-charts/save-cloud/values.yaml
Labels: infra

#1903 Bugfix for demo run request
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/DemoRunComponent.kt
Labels: frontend

#1906 Agent Jobs should be deleted on completion
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/config/ConfigProperties.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/kubernetes/KubernetesManager.kt
Labels: enhancement, infra

#1910 Replace port-forwarding with Service
  save-cloud-charts/save-cloud/templates/demo-agent-service.yaml
  save-cloud-charts/save-cloud/templates/demo-configmap.yaml
  save-cloud-charts/save-cloud/values.yaml
  save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
  save-demo/src/test/kotlin/com/saveourtool/save/demo/utils/HttpUtilsTest.kt
Labels: enhancement
