Repository saveourtool/save-cloud, pull requests merged in 2023-09, with the labels that each got.

#2518 Refactoring Vulnerability Creation
  authentication-service/src/main/kotlin/com/saveourtool/save/authservice/config/WebSecurityConfig.kt
  db/test-data/sqlRequests/vulnerability.csv
  db/test-data/vulnerability-insert.xml
  db/v-2/tables/vulnerability.xml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityDateRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityProjectRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/vulnerability/VulnerabilityRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/security/VulnerabilityPermissionEvaluator.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectProblemService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TagService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/ProjectProblemDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDateDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityProjectDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/filters/VulnerabilityFilter.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/ProjectProblem.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/Vulnerability.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/VulnerabilityDate.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/vulnerabilities/VulnerabilityProject.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/AbstractCosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesTab.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/CreateProjectProblemView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/EditProjectProblemWindow.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectProblemView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/table/filters/VulnerabilitiesFiltersRow.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityDateModal.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/FilterParamUtils.kt
Labels: refactoring, vulnerabilities

#2526 Added missed fields to COSV metadata
  db/v-2/tables/cosv-metadata.xml
  db/v-2/tables/db.changelog-tables.xml
  db/v-2/tables/lnk-cosv-metadata-tag.xml
  gradle/libs.versions.toml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/BackendForCosvService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/OrganizationService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/UserDetailsService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DatabaseTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/JpaSpecificationTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/LnkUserOrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt
  save-cloud-common/build.gradle.kts
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadataDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/RawCosvExt.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/CosvSchemaUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadata.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/LnkCosvMetadataTag.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IBackendService.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IOrganizationService.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/backend/service/IUserService.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/AbstractCosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/LnkCosvMetadataTagRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
Labels: vulnerabilities

#2534 Generate identifier checkbox
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
Labels: enhancement, vulnerabilities

#2539 A single CosvProcesor for all files
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/controllers/CosvController.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/AbstractCosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/CosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/CosvProcessorHolder.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/DefaultCosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/go/GoCosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/go/GoImports.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/go/GoUrl.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
Labels: vulnerabilities

#2542 Invalid request params
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
Labels: frontend, vulnerabilities

#2545 Generating COSV for manually created vulnerabilities
  db/v-2/tables/cosv-metadata.xml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/CosvSchemaUtils.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
Labels: vulnerabilities

#2546 ThanksForRegistrationView
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/validation/FrontendRoutes.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/BanView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ThanksForRegistrationView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/locales/Translations.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
Labels: enhancement, frontend

#2549 Added link repositories for COSV
  db/v-2/tables/cosv-metadata-project.xml
  db/v-2/tables/lnk-cosv-metadata-user.xml
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DatabaseTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/JpaSpecificationTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/LnkUserOrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/LnkProjectVulnerabilityDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadataProjectDto.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadataProject.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/LnkCosvMetadataUser.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvMetadataProjectRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/LnkCosvMetadataUserRepository.kt
Labels: vulnerabilities

#2552 Not approved should work
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/UserDetailsService.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/UsersDetailsControllerTest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/UserSaveStatus.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/BanView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ThanksForRegistrationView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/CustomHooks.kt
Labels: enhancement, frontend

#2553 Let users add some info on registration
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
Labels: enhancement, frontend

#2560 Add GitHub on registration
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputTextFormRequired.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
Labels: enhancement, frontend

#2563 Supported Submitted in timeline
  db/test-data/cosv-metadata-insert.xml
  db/test-data/sqlRequests/cosv-metadata.csv
  db/v-2/tables/cosv-metadata.xml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
  save-backend/src/test/resources/minio/cosv/CVE-2022-22978/2021-01-01T00_00
  save-backend/src/test/resources/minio/cosv/CVE-2022-25296/2021-01-01T00_00
  save-backend/src/test/resources/minio/cosv/CVE-2022-25365/2021-01-01T00_00
  save-backend/src/test/resources/minio/cosv/CVE-2022-44697/2021-01-01T00_00
  save-backend/src/test/resources/minio/cosv/CVE-2023-22475/2021-01-01T00_00
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadataDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/vulnerability/VulnerabilityDateType.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/CosvSchemaUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvMetadata.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityDateModal.kt
Labels: vulnerabilities

#2562 Added UserStatus check to gateway
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
  authentication-service/src/main/kotlin/com/saveourtool/save/authservice/utils/SaveUserDetails.kt
  authentication-service/src/main/kotlin/com/saveourtool/save/authservice/utils/SecurityUtils.kt
  authentication-service/src/test/kotlin/com/saveourtool/save/authservice/utils/SaveUserDetailsTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/security/OrganizationPermissionEvaluatorTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/security/ProjectPermissionEvaluatorTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/utils/SecurityTestingUtils.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/Constants.kt
  save-frontend/README.md
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/usersettings/right/Token.kt
  save-frontend/webpack.config.d/dev-server.js
Labels: enhancement, auth

#2565 registrationView follow-ups
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/RegistrationView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
Labels: frontend

#2573 Hotfix for gateway user status check
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
Labels: enhancement, auth

#2572 Validate vuln identifier on frontend
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/CreateVulnerabilityView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/locales/Translations.kt
Labels: enhancement, frontend

#2575 Hotfix for 403 when user changed name
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/controller/SecurityInfoController.kt
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/service/BackendService.kt
Labels: auth

#2578 Move translations to separate jsons
  save-frontend/build.gradle.kts
  save-frontend/nginx.conf
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/App.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/LanguageSelector.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesTab.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/SaveWelcomeView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/WelcomeUtils.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/Translation.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/locales/Translations.kt
  save-frontend/src/main/resources/locales/cn/cookies.json
  save-frontend/src/main/resources/locales/cn/organization.json
  save-frontend/src/main/resources/locales/cn/proposing.json
  save-frontend/src/main/resources/locales/cn/table-headers.json
  save-frontend/src/main/resources/locales/cn/thanks-for-registration.json
  save-frontend/src/main/resources/locales/cn/topbar.json
  save-frontend/src/main/resources/locales/cn/vulnerability-collection.json
  save-frontend/src/main/resources/locales/cn/vulnerability-upload.json
  save-frontend/src/main/resources/locales/cn/welcome.json
  save-frontend/src/main/resources/locales/en/cookies.json
  save-frontend/src/main/resources/locales/en/organization.json
  save-frontend/src/main/resources/locales/en/proposing.json
  save-frontend/src/main/resources/locales/en/table-headers.json
  save-frontend/src/main/resources/locales/en/thanks-for-registration.json
  save-frontend/src/main/resources/locales/en/topbar.json
  save-frontend/src/main/resources/locales/en/vulnerability-collection.json
  save-frontend/src/main/resources/locales/en/vulnerability-upload.json
  save-frontend/src/main/resources/locales/en/welcome.json
  save-frontend/src/main/resources/locales/ru/cookies.json
  save-frontend/src/main/resources/locales/ru/organization.json
  save-frontend/src/main/resources/locales/ru/proposing.json
  save-frontend/src/main/resources/locales/ru/table-headers.json
  save-frontend/src/main/resources/locales/ru/thanks-for-registration.json
  save-frontend/src/main/resources/locales/ru/topbar.json
  save-frontend/src/main/resources/locales/ru/vulnerability-collection.json
  save-frontend/src/main/resources/locales/ru/vulnerability-upload.json
  save-frontend/src/main/resources/locales/ru/welcome.json
  yarn.lock
Labels: enhancement, frontend

#2579 Renamed `CosvMetadata` to `VulnerabilityMetadata`
  db/test-data/db.changelog-insert.xml
  db/test-data/lnk-vulnerability-metadata-user-insert.xml
  db/test-data/sqlRequests/lnk-vulnerability-metadata-user.csv
  db/test-data/sqlRequests/vulnerability-metadata-project.csv
  db/test-data/sqlRequests/vulnerability-metadata.csv
  db/test-data/vulnerability-metadata-insert.xml
  db/test-data/vulnerability-metadata-project-insert.xml
  db/v-2/tables/db.changelog-tables.xml
  db/v-2/tables/lnk-vulnerability-metadata-tag.xml
  db/v-2/tables/lnk-vulnerability-metadata-user.xml
  db/v-2/tables/project-problem.xml
  db/v-2/tables/vulnerability-metadata-project.xml
  db/v-2/tables/vulnerability-metadata.xml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectProblemService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TagService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DatabaseTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/JpaSpecificationTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/LnkUserOrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityExt.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityMetadataDto.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/ProjectProblem.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/LnkVulnerabilityMetadataTag.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/LnkVulnerabilityMetadataUser.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityMetadata.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/VulnerabilityMetadataProject.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/processor/CosvProcessor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvMetadataProjectRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/LnkCosvMetadataTagRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/LnkCosvMetadataUserRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/LnkVulnerabilityMetadataTagRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/LnkVulnerabilityMetadataUserRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/VulnerabilityMetadataProjectRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/VulnerabilityMetadataRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
Labels: refactoring, vulnerabilities

#2582 IndexView localization
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardAboutUs.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardServiceInfo.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/CardUser.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexLogoButtons.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/index/IndexViewUserInfo.kt
  save-frontend/src/main/resources/locales/en/index.json
  save-frontend/src/main/resources/locales/ru/index.json
Labels: frontend, localization

#2583 Topbar localization follow-ups
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/topbar/TopBarUserField.kt
  save-frontend/src/main/resources/locales/en/topbar.json
  save-frontend/src/main/resources/locales/ru/topbar.json
Labels: frontend, localization

#2584 VulnerabilityWelcomeView localization
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/SaveWelcomeView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/VulnerabilityWelcomeView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/WelcomeUtils.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/welcome/pagers/vuln/WhatIsVuln.kt
  save-frontend/src/main/resources/locales/en/welcome.json
  save-frontend/src/main/resources/locales/ru/proposing.json
  save-frontend/src/main/resources/locales/ru/topbar.json
  save-frontend/src/main/resources/locales/ru/welcome.json
Labels: frontend, localization

#2587 Refactored storage for COSV files
  .run/save-cloud [detektAll].run.xml
  .run/save-cloud [diktatFix].run.xml
  .run/save-cloud [startMinioService].run.xml
  .run/save-cloud [startMysqlService].run.xml
  db/v-2/tables/cosv-file.xml
  db/v-2/tables/db.changelog-tables.xml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/FileStorage.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DatabaseTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/JpaSpecificationTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/LnkUserOrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/OrganizationControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/PermissionControllerTest.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/cosv/CosvFile.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/s3/S3OperationsProperties.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationReactiveStorage.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractReactiveStorage.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/ReactiveStorageWithDatabase.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/StorageInitializer.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/StorageProjectReactor.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvFileRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/CosvFileS3KeyManager.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/CosvFileStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/MigrationCosvObjectStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/storage/RawCosvFileStorage.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/DependencyStorage.kt
Labels: refactoring, vulnerabilities, s3-obs

#2594 VulnerabilityView localization
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/Forum.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TimelineComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityBadge.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCommentTab.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityDateModal.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityGeneralInfo.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityInfoTab.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityProjectWindow.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityTagsComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/i18next/InitI18n.kt
  save-frontend/src/main/resources/locales/en/comments.json
  save-frontend/src/main/resources/locales/en/dates.json
  save-frontend/src/main/resources/locales/en/vulnerability.json
  save-frontend/src/main/resources/locales/ru/comments.json
  save-frontend/src/main/resources/locales/ru/dates.json
  save-frontend/src/main/resources/locales/ru/vulnerability.json
Labels: frontend, localization

#2603 Added a button to download vulnerability in COSV
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/vulnerability/VulnerabilityController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/vulnerability/VulnerabilityService.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepository.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/repository/CosvRepositoryInStorage.kt
  save-cosv/src/main/kotlin/com/saveourtool/save/cosv/service/CosvService.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/vuln/VulnerabilityHeader.kt
  save-frontend/src/main/resources/locales/en/vulnerability.json
  save-frontend/src/main/resources/locales/ru/vulnerability.json
Labels: vulnerabilities

#2620 A try to fix Dockerfile
  save-deploy/base-images/Dockerfile
Labels: infra

#2621 Another try to fix Dockerfile
  .github/workflows/build-base-images.yaml
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/SaveAgent.kt
  save-deploy/base-images/Dockerfile
Labels: infra

#2638 Fixed issue with multiple select of test suites
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuitesSourceDto.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectRunMenu.kt
Labels: bug

#2639 One contest per execution
  db/test-data/sqlRequests/lnk-contest-execution.csv
  db/v-2/tables/lnk-contest-execution.xml
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ExecutionController.kt
Labels: bug
