Repository saveourtool/save-cloud, pull requests merged in 2023-01, with the labels that each got.

#1699 Added AbstractMigrationStorage
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/MigrationFileStorage.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/entities/FileDto.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationStorage.kt
  save-orchestrator-common/src/main/kotlin/com/saveourtool/save/orchestrator/utils/AgentStatusInMemoryRepository.kt
Labels: refactoring

#1701 Fix the way empty debug info is added to each test execution
  .gitignore
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
Labels: frontend

#1715 Properly escape URL parameters when requesting `/test-executions`
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/ExecutionView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/utils/RequestUtils.kt
Labels: frontend

#1735 UI improvements
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/test/analysis/TestMetricsView.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/routing/BasicRouting.kt
Labels: frontend

#1739 Enable build scan publishing for GitHub Action-triggered builds
  gradle.properties
  settings.gradle.kts
Labels: infra

#1742 Fixed copying `Test` when `TestSuite` is copied
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
Labels: bug

#1751 Make `repository` available for child in `AbstractStorageWithDatabase`
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/FileStorage.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractStorageWithDatabase.kt
Labels: refactoring

#1752 Move marking execution as `OBSOLETE` on deletion of test suites to ExecutionService
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/LnkExecutionTestSuiteRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/LnkExecutionTestSuiteService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
Labels: refactoring

#1756 Make sure artifact signing is applied after Maven configurations are created (take 2)
  .github/workflows/save-api-release.yml
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/PublishingConfiguration.kt
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/publishing-configuration.gradle.kts
  save-cloud-common/build.gradle.kts
Labels: infra

#1717 Add metadata about test suites source snapshots in database
  db/test-data/db.changelog-insert.xml
  db/test-data/sqlRequests/tests-source-snapshot.csv
  db/test-data/sqlRequests/tests-source-version.csv
  db/test-data/test-suite-insert.xml
  db/test-data/tests-source-snapshot-insert.xml
  db/test-data/tests-source-version-insert.xml
  db/v-2/tables/tests-source-version.xml
  gradle/libs.versions.toml
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkOrganizationTestSuiteController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestSuitesController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/TestSuitesSourceInternalController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestSuiteRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestSuitesSourceRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestsSourceSnapshotRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/repository/TestsSourceVersionRepository.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ExecutionService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestSuitesSourceService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/TestsSourceVersionService.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/storage/TestsSourceSnapshotStorage.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controller/TestSuitesControllerTest.kt
  save-backend/src/test/kotlin/com/saveourtool/save/backend/controllers/RunExecutionControllerTest.kt
  save-cloud-common/build.gradle.kts
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/request/CreateExecutionRequest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/testsuite/TestSuiteDto.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/Contest.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestSuite.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/entities/TestsSourceSnapshot.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractMigrationStorage.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractStorageWithDatabase.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/OrganizationTestsMenu.kt
  save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/controllers/TestSuitesPreprocessorController.kt
  save-preprocessor/src/main/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringService.kt
  save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/controllers/TestSuitesPreprocessorControllerTest.kt
  save-preprocessor/src/test/kotlin/com/saveourtool/save/preprocessor/service/TestDiscoveringServiceTest.kt
Labels: enhancement, refactoring

#1759 [DEMO] upload, get and delete files manually
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/GithubRepo.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Tool.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/GithubRepoRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubRepoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolKey.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolStorage.kt
Labels: enhancement

#1769 File uploader refactoring
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/SdkSelection.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/FileUploaderWrappers.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/HeavyFileUploader.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/SimpleFileUploader.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectRunMenu.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/SandboxView.kt
Labels: enhancement, frontend

#1767 [DEMO] make GitHub download optional
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoDto.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/domain/ProjectCoordinates.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/GithubDownloadToolService.kt
  save-demo/src/main/resources/application.properties
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
Labels: enhancement

#1772 [DEMO] file uploading on frontend
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
Labels: enhancement, frontend

#1776 When fetching test suites, use the overloaded `post()` version and `jso {}` to construct request parameters
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/testsuitessources/fetch/TestSuitesSourceFetcher.kt
Labels: frontend

#1779 [DEMO] upload files from FileStorage to ToolStorage
  api-gateway/src/main/kotlin/com/saveourtool/save/gateway/security/WebSecurityConfig.kt
  save-backend/backend-api-docs.json
  save-backend/src/main/kotlin/com/saveourtool/save/backend/SaveApplication.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ContestController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DemoManagerController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/DownloadFilesController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/FileController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkContestProjectController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkOrganizationTestSuiteController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/LnkUserOrganizationController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/OrganizationController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/ProjectController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/RunExecutionController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/TestSuitesSourceController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/internal/UsersController.kt
  save-backend/src/main/kotlin/com/saveourtool/save/backend/service/ProjectService.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoCreationRequest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoStatus.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/KotlinUtilsJvm.kt
  save-demo/db/tables/db.changelog-tables.xml
  save-demo/db/tables/dependency.xml
  save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/ManagementController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/entity/Dependency.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/repository/DependencyRepository.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DependencyService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DownloadToolService.kt
  save-demo/src/main/resources/application-dev.properties
  save-demo/src/main/resources/application.properties
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/fileuploader/SimpleFileUploader.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/projects/ProjectDemoMenu.kt
  save-sandbox/src/main/kotlin/com/saveourtool/save/sandbox/controller/SandboxInternalController.kt
Labels: enhancement, help wanted

#1787 Avoid calling `block()` on a `MonoMapFuseable` within a non-blocking …
  save-backend/src/test/kotlin/com/saveourtool/save/backend/DownloadFilesTest.kt
Labels: testing

#1792 save-demo-agent template
  gradle/libs.versions.toml
  save-demo-agent/build.gradle.kts
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/Main.kt
  save-demo-agent/src/nativeTest/kotlin/com/saveoourtool/save/demo/agent/MainTest.kt
  settings.gradle.kts
Labels: enhancement, help wanted
