Repository saveourtool/save-cloud, pull requests merged in 2023-04, with the labels that each got.

#2062 save-demo-agents isolation pt I
  save-cloud-charts/save-cloud/templates/agent-namespace.yaml
  save-cloud-charts/save-cloud/templates/agent-service.yaml
  save-cloud-charts/save-cloud/templates/demo-configmap.yaml
  save-cloud-charts/save-cloud/templates/demo-service-account.yaml
  save-cloud-charts/save-cloud/values.yaml
  save-demo/src/main/kotlin/com/saveourtool/save/demo/config/Beans.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/config/ConfigProperties.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
  save-demo/src/main/resources/application-minikube.properties
  save-demo/src/test/kotlin/com/saveourtool/save/demo/utils/HttpUtilsTest.kt
Labels: enhancement, help wanted, infra

#2066 KubernetesServiceAccountAuthHeaderPlugin
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/Main.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/SaveAgent.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/HttpUtils.kt
  save-agent/src/commonMain/kotlin/com/saveourtool/save/agent/utils/PlatformUtils.kt
  save-agent/src/jvmMain/kotlin/com/saveourtool/save/agent/utils/PlatformUtils.kt
  save-agent/src/linuxX64Main/kotlin/com/saveourtool/save/agent/utils/PlatformUtils.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/HttpUtils.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt
  save-cloud-common/src/jsMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt
  save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt
  save-cloud-common/src/nativeMain/kotlin/com/saveourtool/save/utils/PlatformUtils.kt
  save-demo-agent/src/nativeMain/kotlin/com/saveourtool/save/demo/agent/utils/HttpUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DownloadToolService.kt
Labels: enhancement, help wanted

#2068 Replace DiktatCliRunner with PodRunner
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoInfo.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoMode.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/DemoRunRequest.kt
  save-cloud-common/src/commonMain/kotlin/com/saveourtool/save/demo/diktat/DiktatDemoTool.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/controller/DiktatDemoController.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/runners/cli/DiktatCliRunner.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/AbstractDemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DiktatDemoService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/DownloadToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/KubernetesService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/service/ToolService.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/DependencyKeyManager.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/DependencyStorage.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/storage/ToolKey.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/Constants.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt
  save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/KubernetesUtils.kt
  save-demo/src/test/kotlin/com/saveourtool/save/demo/runners/cli/CommandBuilderTest.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/run/DemoOutputComponent.kt
  save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/demo/run/DemoRunComponent.kt
Labels: refactoring, demo

#2087 Add maven.pkg.github.com to the list of hosts recognized by Renovate
  renovate.json
Labels: infra

#2088 Upgrade `io.github.oxisto:kotlin-tree-jna` to version 0.0.2
  save-demo-cpg/build.gradle.kts
Labels: infra

#2112 Dependency in building
  .github/workflows/build_and_test.yml
  .github/workflows/build_and_test_reusable.yml
  .github/workflows/build_save-cli_reusable.yml
  .github/workflows/deploy_images.yml
  .github/workflows/deploy_images_reusable.yml
  gradle/plugins/src/main/kotlin/com/saveourtool/save/buildutils/save-agent-configuration.gradle.kts
  save-agent/build.gradle.kts
  save-demo-agent/build.gradle.kts
Labels: infra

#2116 Fix deploy_images_reusable.yml
  .github/workflows/deploy_images_reusable.yml
Labels: infra

#2120 Fix deploy_images_reusable.yml
  .github/workflows/deploy_images.yml
  .github/workflows/deploy_images_reusable.yml
Labels: infra

#2123 Fix backend-api-spec-update.yml
  .github/workflows/backend-api-spec-update.yml
Labels: infra
